import = [
    "~/.config/alacritty/tokyonight_storm.toml",
]

live_config_reload = true

[cursor]
style = "Beam"
vi_mode_style = "Block"
thickness = 0.15

[font]
bold = { family = "SFMono Nerd Font" }
bold_italic = { family = "SFMono Nerd Font" }
italic = { family = "SFMono Nerd Font" }
normal = { family = "SFMono Nerd Font" }
offset = { x = 1, y = 1 }
size = 13.0

[mouse]
hide_when_typing = true

[scrolling]
history = 100000
multiplier = 1

[selection]
save_to_clipboard = true

[window]
decorations = "full"
dynamic_padding = true
dynamic_title = true
option_as_alt = "both"
startup_mode = "Windowed"
title = "Alacritty"
