import:
  - ~/.config/alacritty/tokyonight_storm.yml

window:
  dimensions:
    columns: 200
    lines: 50
  padding:
    x: 3
    y: 5
  dynamic_padding: true
  decorations: full
  startup_mode: Windowed
  title: Alacritty
  dynamic_title: true

scrolling:
  history: 100000
  multiplier: 1

font:
  size: 13.0
  offset:
    x: 1
    y: 1
  normal:
    family: SF Mono
  bold:
    family: SF Mono
  italic:
    family: SF Mono
  bold_italic:
    family: SF Mono

draw_bold_text_with_bright_colors: false

selection:
  save_to_clipboard: true

cursor:
  style: Beam
  vi_mode_style: Block
  unfocused_hollow: true
  thickness: 0.15

live_config_reload: true
working_directory: None

mouse:
  hide_when_typing: false
  double_click:
    threshold: 300
