window:
  dimensions:
    columns: 120
    lines: 30
  padding:
    x: 3
    y: 5
  dynamic_padding: true
  decorations: full
  startup_mode: Windowed
  title: Alacritty
  dynamic_title: true

scrolling:
  history: 100000
  multiplier: 1

font:
  size: 13.0
  use_thin_strokes: true
  offset:
    x: 1
    y: 1
  normal:
    family: SF Mono
  bold:
    family: SF Mono
  italic:
    family: SF Mono
  bold_italic:
    family: SF Mono

draw_bold_text_with_bright_colors: false
# Colors (Gruvbox dark)
colors:
  # Default colors
  primary:
    # hard contrast: background = '#1d2021'
    background: '#282828'
    # soft contrast: background = '#32302f'
    foreground: '#ebdbb2'

  # Normal colors
  normal:
    black:   '#282828'
    red:     '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#689d6a'
    white:   '#a89984'

  # Bright colors
  bright:
    black:   '#928374'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#8ec07c'
    white:   '#ebdbb2'

selection:
  save_to_clipboard: true

cursor:
  style: Beam
  vi_mode_style: Block
  unfocused_hollow: true
  thickness: 0.15

live_config_reload: true
working_directory: None

mouse:
  hide_when_typing: false
  double_click:
    threshold: 300
