#!/usr/bin/env sh


__source_if_file_exists () {
    if [ -r "$1" ]; then
        # shellcheck disable=SC1090
        . "$1"
    fi
}


__add_to_path () {
    if ! echo ":${PATH}:" | grep -oq ":${1}:"; then
        export PATH="${PATH}:${1}"
    fi
}


rreadlink () (
    target_file="$1"

    if [ ! -e "$target_file" ]; then
        echo "${target_file}: no such file or directory"
        return 2
    elif [ "$(uname)" != "Darwin" ]; then
        readlink -f "$target_file"
        return $?
    fi

    max_links_followed=1000
    links_followed=0
    while [ -L "$target_file" ]; do
        if ! cd "$(dirname "$target_file")" >/dev/null 2>/dev/null; then
            return 2
        fi
        target_file="$(readlink "$(basename "$target_file")")"

        links_followed="$((links_followed + 1))"
        if [ "$links_followed" -ge "$max_links_followed" ]; then
            original_file
            original_file="$1"
            echo "${original_file}: maximum number of symlinks followed. Using ${target_file}" 1>&2
            break
        fi
    done

    if ! cd "$(dirname "$target_file")" >/dev/null 2>/dev/null; then
        return 2
    fi

    echo "$(pwd -P)/$(basename "$target_file")"
)


__add_to_path "/usr/local/sbin"
__add_to_path "${HOME}/.local/bin"


export XDG_CACHE_HOME="${XDG_CACHE_HOME:-${HOME}/.cache}"
export XDG_CONFIG_DIRS="${XDG_CONFIG_DIRS:-/etc/xdg}"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-${HOME}/.config}"
export XDG_DATA_DIRS="${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}"


if [ -z "$PS1" ] || ! echo "$-" | grep -q "i"; then
    # shell is not interactive
    return
fi


export CLICOLOR=1
export EDITOR="nvim"
export HISTCONTROL="ignoredups"
export HISTFILESIZE=100000
export HISTSIZE=100000
export VISUAL="$EDITOR"


alias edit="\$EDITOR"
alias finagle="edit ~/.finagle"
alias less="less -r"
alias vim="nvim"


alias ..="cd ../"
alias ...="cd ../../"
alias ....="cd ../../../"


alias ls="ls -hF"
alias la="ls -A"
alias ll="ls -l"
alias lla="ll -A"


alias cp="cp -vi"
alias mv="mv -vi"
alias rm="rm -vi"
alias mkdir="mkdir -pv"


alias g="git"


alias gw="./gradlew"


if [ -z "$JAVA_HOME" ] && /usr/libexec/java_home >/dev/null 2>/dev/null; then
    JAVA_HOME="$(/usr/libexec/java_home)"
    export JAVA_HOME="$JAVA_HOME"
fi


if [ -z "$GROOVY_HOME" ] && [ -d "/usr/local/opt/groovy/libexec" ]; then
    GROOVY_HOME="/usr/local/opt/groovy/libexec"
    export GROOVY_HOME="$GROOVY_HOME"
fi


if [ -z "$RIPGREP_CONFIG_PATH" ] && [ -r "${XDG_CONFIG_HOME}/ripgrep/ripgreprc" ]; then
    RIPGREP_CONFIG_PATH="${XDG_CONFIG_HOME}/ripgrep/ripgreprc"
    export RIPGREP_CONFIG_PATH
fi


# shellcheck disable=SC2009
if ! ps -p "$$" -o command= | grep -q "bash$"; then
    # shell is not bash
    return
fi


# shellcheck disable=SC2039,SC3028,SC3054
DOTFILES_DIR="$(git -C "$(dirname "$(rreadlink "${BASH_SOURCE[0]}")")" rev-parse --show-toplevel)"
export DOTFILES_DIR
__add_to_path "${DOTFILES_DIR}/bin"


# shellcheck source=./shell/bash_config.sh
__source_if_file_exists "${DOTFILES_DIR}/shell/bash_config.sh"
