#!/usr/bin/env bash
# bash_aliases

# better reading
alias less='less -r'
alias vi='vim'

# random
alias finagle='vim ~/.finagle'

# navigation
alias back='cd -'
alias ..='cd ../'
alias ...='cd ../../'
alias ....='cd ../../../'
alias ls='ls -hF'
alias la='ls -A'
alias ll='ls -l'
alias lla='ll -A'

# filesystem safety
alias cp='cp -vi'
alias mv='mv -vi'
alias rm='rm -vi'
alias mkdir='mkdir -pv'

# git aliases
alias g='git'
__git_complete g _git

# fuck
if which thefuck > /dev/null 2>&1; then
    eval "$(thefuck --alias)"
fi

# clipboards
if [ "$(uname)" == "Linux" ]; then
    alias pbcopy='xclip -selection clipboard'
    alias pbpaste='xclip -selection clipboard -o'
fi

