#!/usr/bin/env bash
# bash_prompt

__git_prompt () {
    if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
        return 0
    fi

    local LOCAL_BRANCH="$(git rev-parse --symbolic-full-name --abbrev-ref HEAD 2> /dev/null)"
    local REMOTE_BRANCH="$(git rev-parse --symbolic-full-name --abbrev-ref @{upstream} 2> /dev/null)"
    local LOCAL_REMOTE_DIFF=$(git rev-list --left-right --count "${LOCAL_BRANCH}"..."${REMOTE_BRANCH}" 2> /dev/null)

    local LOCAL_AHEAD=$(echo $LOCAL_REMOTE_DIFF | awk '{ print $1 }')
    if [ -n "$LOCAL_AHEAD" ] && [ $LOCAL_AHEAD -ne 0 ]; then
        local LOCAL_STATUS_STRING="\u2191${LOCAL_AHEAD}"
    fi

    local REMOTE_AHEAD=$(echo $LOCAL_REMOTE_DIFF | awk '{ print $2 }')
    if [ -n "$REMOTE_AHEAD" ] && [ $REMOTE_AHEAD -ne 0 ]; then
        local REMOTE_STATUS_STRING="\u2191${REMOTE_AHEAD}"
    fi

    printf "\[$(tput setaf 1)\]%s%b|%s%b" "$LOCAL_BRANCH" "$LOCAL_STATUS_STRING" "$REMOTE_BRANCH" "$REMOTE_STATUS_STRING"
}

__time_and_date () {
    printf "$(date +%R)"
}

__previous_return_status () {
    if [ $1 -eq 0 ]; then
        printf "\[$(tput setaf 2)\]\u2713"
    else
        printf "\[$(tput setaf 1)\]\u2717"
    fi
}

__prompt_command () {
    local EXIT_CODE=$?
    export PROMPT_DIRTRIM=3
    local DATE_STRING="\[$(tput setaf 0)\]$(__time_and_date)"
    local HOST_STRING
    if [[ "$(hostname --short)" == "sswanson3-linux" ]]; then
        # my linux machines will use a green prompt leader
        HOST_STRING="\[$(tput setaf 2)\]\h"
    else
        # other machines will use a blue prompt leader
        HOST_STRING="\[$(tput setaf 1)\]\h"
    fi
    local CWD_STRING="\[$(tput setaf 3)\]\w"
    local GIT_STRING="$(__git_prompt)"
    local RETURN_STRING="$(__previous_return_status $EXIT_CODE)"
    export PS1="${HOST_STRING} ${CWD_STRING} ${GIT_STRING} ${OLDPWD_STRING} ${DATE_STRING}\n${RETURN_STRING} \[$(tput sgr0)\]$ "
}

PROMPT_COMMAND=__prompt_command

