" vimrc
" Settings that don't really fit into any of the files in the plugin directory.

set nocompatible
set history=1000

let mapleader=","
let maplocalleader="'"

filetype plugin indent on

set backspace=eol,indent,start
set foldenable
set foldmethod=syntax
set nojoinspaces
set nrformats-=octal

if has("unnamedplus")
  set clipboard^=unnamedplus
elseif has("clipboard")
  set clipboard^=unnamed
endif

if !exists('$LANG') && &encoding ==# "latin1"
  set encoding=utf-8
endif

if has("mouse")
  set mouse=a
endif

" These files are under the vim directory but excluded from git.
set directory^=$HOME/.vim/.caches/swapfiles//
set undodir^=$HOME/.vim/.caches/undo//
set undofile
