" vimrc
" Simon Swanson

set nocompatible

set history=1000

let mapleader=','

" don't reload screen during batch processing
set lazyredraw

" line numbers on by default
set number

" escape in insert mode should be final: don't wait for other keys
set noesckeys

" load filetype settings and plugins
if has('autocmd')
    " on my keyboard I've put tilde in a pretty good position for a leader key
    let maplocalleader='`'
    filetype plugin indent on
endif

" load features dependent on syntax
if has('syntax')
    if !exists('g:syntax_on')
        syntax enable
    endif

    set background=dark
endif

" find the current line more easily
set cursorline

" default settings that filetype plugins should override
set comments=
set include=
set path-=/usr/include/
set textwidth=0

" use UTF-8 when possible
if has('multi_byte') && !exists('$LANG') && &encoding ==# 'latin1'
    set encoding=utf-8
endif

" backspace behaves as most expect
set backspace+=eol
set backspace+=indent
set backspace+=start

" default indentation settings
" filetype plugins should make adjustments as necessary
set autoindent
set expandtab
set shiftwidth=4
set softtabstop=4

" indent wrapped lines
set breakindent

" delete comment leaders when joining lines
set formatoptions+=j

" don't join with extra spaces
set nojoinspaces

" search settings
set incsearch
set hlsearch
set smartcase
if 1
    nohlsearch " clear search highlights on reload
endif

" line breaks on words
set linebreak

" make reading invisible characters easier
set listchars+=extends:→
set listchars+=precedes:←
set listchars+=nbsp:·
set listchars+=tab:»·
set listchars+=trail:·

" completion settings
set wildignorecase
set wildmenu
set wildmode=list:longest
if exists('+completeopt')
    set completeopt=longest,menuone,preview
endif

" enable potential folding
if has('folding')
    set foldlevelstart=99
    set foldmethod=indent
endif

" wrapped rows start with 3 dots
set showbreak=...

" sane split settings
set splitbelow
set splitright

" connect to system clipboard
if has('unnamedplus')
    set clipboard^=unnamedplus
elseif has('clipboard')
    set clipboard^=unnamed
endif

" buffers can have changes without being displayed
set hidden

" keep backups, swapfiles, undo, and plugin data in an appropriate place
set backup
set backupdir^=$HOME/.vim/.caches/backups//
set directory^=$HOME/.vim/.caches/swapfiles//
if has('persistent_undo')
    set undofile
    set undodir^=$HOME/.vim/.caches/undo//
endif

" leading 0 in number is decimal, not octal
set nrformats-=octal

