set nocompatible
set history=1000

let mapleader=","
let maplocalleader="'"

set backspace=eol,indent,start

set autoindent
set expandtab
set shiftwidth=4
set softtabstop=4

set ignorecase
set incsearch
set hlsearch
set smartcase

set cmdheight=2
set cursorline
set number
set signcolumn=number
set textwidth=0

set breakindent
set linebreak
set showbreak=...

set foldenable
set foldmethod=syntax
set foldlevel=99

set hidden
set lazyredraw
set splitbelow
set splitright

set completeopt=longest,menuone,preview

set wildignorecase
set wildmenu
set wildmode=list:longest

set formatoptions=cjloqrt1
set nojoinspaces

set listchars=eol:$,extends:→,precedes:←,nbsp:·,tab:»·,trail:·

filetype plugin indent on

set comments=
set include=
set nrformats-=octal
set path-=/usr/include/

if has("unnamedplus")
  set clipboard^=unnamedplus
elseif has("clipboard")
  set clipboard^=unnamed
endif

if !exists('$LANG') && &encoding ==# "latin1"
  set encoding=utf-8
endif

if has("mouse")
  set mouse=a
endif

" The .caches directory is excluded from git
set directory^=$HOME/.vim/.caches/swapfiles//
set undodir^=$HOME/.vim/.caches/undo//
set undofile

" Clear highlights when configuration loaded
nohlsearch
