[user]
name = "Simon Swanson"
email = "gitlab@simonswanson.xyz"

[ui]
diff-formatter = ":git"
editor = "nvim"
pager = "delta"
default-command = "status"

[merge-tools.delta]
diff-expected-exit-codes = [0, 1]

[experimental-advance-branches]
enabled-branches = ["glob:*"]

[revset-aliases]
# Closest revision that is mutable, described and either non-empty or a merge
'closest_pushable(to)' = '''
  heads(::to & mutable() & ~description(exact:"") & (~empty() | merges()))
'''

[revsets]
bookmark-advance-to = 'closest_pushable(@)'

[aliases]
pull = ["util", "exec", "--", "bash", "-c", "jj fetch && jj mergein", ""]
pushup = ["util", "exec", "--", "bash", "-c", "jj bookmark advance && jj git push", ""]
fetch = ["git", "fetch"]
mergein = ["rebase", "-d", "trunk()"]
w = ["new"]
checkpoint = ["commit", "-m", "checkpoint"]
verboselog = ["log", "-T", "builtin_log_detailed"]
