[user]
name = "Simon Swanson"
email = "gitlab@simonswanson.xyz"

[ui]
diff-formatter = ":git"
editor = "nvim"
pager = "delta"
default-command = "status"

[merge-tools.delta]
diff-expected-exit-codes = [0, 1]
