name: Lint

on:
  push:
    branches:
      - master
    pull_request:
      branches:
        - "*"

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: shellcheck
        uses: bewuethr/shellcheck-action@v2
